In [1]:
from pandas import read_csv

df = read_csv('Carteira.csv')

df

     Ativo  Quantidade  Compra (R$) Data da Compra
0    ITSA4         300       13.060     12/07/2019
1    ITUB4         900       35.270     13/01/2020
2    ITUB4         500       37.600     24/07/2019
3   SANB11         100       29.130     19/08/2020
4    WEGE3         180       33.715     12/08/2020
5    WEGE3          20       35.930     08/03/2021
6   BTLG11           3      112.150     23/07/2021
7   RECR11           3      105.120     23/07/2021
8   MCCI11           3      103.260     23/07/2021
9   PVBI11           3       96.540     23/07/2021
10  RBRP11           3       82.920     23/07/2021
11  HGRU11           3      120.780     23/07/2021
12  XPLG11           3      112.130     23/07/2021
13  MALL11           3       99.600     23/07/2021
14  ALZR11           3      124.200     23/07/2021
15  VGIP11           3      102.190     23/07/2021
16  VILG11           3      117.720     23/07/2021
17  XPML11           3      102.890     23/07/2021
18  VISC11           3      111.710     23/07/2021
19  HGLG11           3      169.150     23/07/2021
20  VRTA11           3      112.250     23/07/2021
21  IRDM11           3      117.690     23/07/2021
22  BTLG11          30      108.710     19/08/2021
23  RECR11          32      102.680     19/08/2021
24  MCCI11          32      101.400     19/08/2021
25  XPLG11          32      101.750     19/08/2021
26  RBRP11          44       74.780     19/08/2021
27  PVBI11          35       93.150     19/08/2021
28  HGRU11          28      115.400     19/08/2021
29  HGLG11          20      163.790     19/08/2021
30  MALL11          36       91.690     19/08/2021
31  VGIP11          33       99.780     19/08/2021
32  ALZR11          28      114.600     19/08/2021
33  VRTA11          30      107.500     19/08/2021
34  IRDM11          29      111.400     19/08/2021
35  VILG11          30      107.890     19/08/2021
36  VISC11          32      102.200     19/08/2021
37  VISC11          32      102.240     19/08/2021
38  BTLG11          11      105.780     16/09/2021
39  RECR11          11      104.800     16/09/2021
40  MCCI11          11      100.940     16/09/2021
41  PVBI11          13       89.220     16/09/2021
42  RBRP11          16       73.730     16/09/2021
43  HGRU11          10      115.600     16/09/2021
44  XPLG11          12       98.400     16/09/2021
45  HGLG11           7      162.620     16/09/2021
46  MALL11          12       95.950     16/09/2021
47  VGIP11          11      100.200     16/09/2021
48  ALZR11          10      115.850     16/09/2021
49  VRTA11          11      108.310     16/09/2021
50  VILG11          11      108.180     16/09/2021
51  VISC11          11      102.120     16/09/2021
52  XPML11          11      101.790     16/09/2021
53  IRDM11          10      114.520     16/09/2021

Se todas as linhas fossem de um mesmo ativo, era só fazer

In [7]:
df['Soma Ponderada (R$)'] = df['Quantidade'] * df['Compra (R$)']

SomaPesos = df['Quantidade'].sum()

SomaTotal = df['Soma Ponderada (R$)'].sum()

media = SomaTotal/SomaPesos

df.drop(columns = 'Soma Ponderada', inplace = True)

df
# print(media)

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
0    ITSA4         300       13.060     12/07/2019              3918.00
1    ITUB4         900       35.270     13/01/2020             31743.00
2    ITUB4         500       37.600     24/07/2019             18800.00
3   SANB11         100       29.130     19/08/2020              2913.00
4    WEGE3         180       33.715     12/08/2020              6068.70
5    WEGE3          20       35.930     08/03/2021               718.60
6   BTLG11           3      112.150     23/07/2021               336.45
7   RECR11           3      105.120     23/07/2021               315.36
8   MCCI11           3      103.260     23/07/2021               309.78
9   PVBI11           3       96.540     23/07/2021               289.62
10  RBRP11           3       82.920     23/07/2021               248.76
11  HGRU11           3      120.780     23/07/2021               362.34
12  XPLG11           3      112.130     23/07/2021               336.39
13  MALL11           3       99.600     23/07/2021               298.80
14  ALZR11           3      124.200     23/07/2021               372.60
15  VGIP11           3      102.190     23/07/2021               306.57
16  VILG11           3      117.720     23/07/2021               353.16
17  XPML11           3      102.890     23/07/2021               308.67
18  VISC11           3      111.710     23/07/2021               335.13
19  HGLG11           3      169.150     23/07/2021               507.45
20  VRTA11           3      112.250     23/07/2021               336.75
21  IRDM11           3      117.690     23/07/2021               353.07
22  BTLG11          30      108.710     19/08/2021              3261.30
23  RECR11          32      102.680     19/08/2021              3285.76
24  MCCI11          32      101.400     19/08/2021              3244.80
25  XPLG11          32      101.750     19/08/2021              3256.00
26  RBRP11          44       74.780     19/08/2021              3290.32
27  PVBI11          35       93.150     19/08/2021              3260.25
28  HGRU11          28      115.400     19/08/2021              3231.20
29  HGLG11          20      163.790     19/08/2021              3275.80
30  MALL11          36       91.690     19/08/2021              3300.84
31  VGIP11          33       99.780     19/08/2021              3292.74
32  ALZR11          28      114.600     19/08/2021              3208.80
33  VRTA11          30      107.500     19/08/2021              3225.00
34  IRDM11          29      111.400     19/08/2021              3230.60
35  VILG11          30      107.890     19/08/2021              3236.70
36  VISC11          32      102.200     19/08/2021              3270.40
37  VISC11          32      102.240     19/08/2021              3271.68
38  BTLG11          11      105.780     16/09/2021              1163.58
39  RECR11          11      104.800     16/09/2021              1152.80
40  MCCI11          11      100.940     16/09/2021              1110.34
41  PVBI11          13       89.220     16/09/2021              1159.86
42  RBRP11          16       73.730     16/09/2021              1179.68
43  HGRU11          10      115.600     16/09/2021              1156.00
44  XPLG11          12       98.400     16/09/2021              1180.80
45  HGLG11           7      162.620     16/09/2021              1138.34
46  MALL11          12       95.950     16/09/2021              1151.40
47  VGIP11          11      100.200     16/09/2021              1102.20
48  ALZR11          10      115.850     16/09/2021              1158.50
49  VRTA11          11      108.310     16/09/2021              1191.41
50  VILG11          11      108.180     16/09/2021              1189.98
51  VISC11          11      102.120     16/09/2021              1123.32
52  XPML11          11      101.790     16/09/2021              1119.69
53  IRDM11          10      114.520     16/09/2021              1145.20

In [8]:
media

51.33656650787835

In [25]:
# df.filter(like = 'ITUB4',
#           axis = 0)

df.loc[df['Ativo'] == 'IRDM11']

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
21  IRDM11           3       117.69     23/07/2021               353.07
34  IRDM11          29       111.40     19/08/2021              3230.60
53  IRDM11          10       114.52     16/09/2021              1145.20

In [35]:
set(df['Ativo'])

{'ALZR11',
 'BTLG11',
 'HGLG11',
 'HGRU11',
 'IRDM11',
 'ITSA4',
 'ITUB4',
 'MALL11',
 'MCCI11',
 'PVBI11',
 'RBRP11',
 'RECR11',
 'SANB11',
 'VGIP11',
 'VILG11',
 'VISC11',
 'VRTA11',
 'WEGE3',
 'XPLG11',
 'XPML11'}

In [31]:
for nome in set(df['Ativo']):
    print(nome)

ITUB4
XPML11
HGLG11
BTLG11
ALZR11
RECR11
SANB11
ITSA4
VILG11
VISC11
MCCI11
MALL11
VRTA11
IRDM11
VGIP11
PVBI11
WEGE3
RBRP11
XPLG11
HGRU11

Agora que vimos como criar um conjunto contendo valores únicos de uma lista, vamos criar sub DataFrames da tabela original

In [41]:
conjunto = set(df['Ativo'])

for nome in conjunto:
    print(df.loc[df['Ativo'] == nome] )
    print()

   Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
1  ITUB4         900        35.27     13/01/2020              31743.0
2  ITUB4         500        37.60     24/07/2019              18800.0

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
17  XPML11           3       102.89     23/07/2021               308.67
52  XPML11          11       101.79     16/09/2021              1119.69

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
19  HGLG11           3       169.15     23/07/2021               507.45
29  HGLG11          20       163.79     19/08/2021              3275.80
45  HGLG11           7       162.62     16/09/2021              1138.34

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
6   BTLG11           3       112.15     23/07/2021               336.45
22  BTLG11          30       108.71     19/08/2021              3261.30
38  BTLG11          11       105.78     16/09/2021              1163.58

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
14  ALZR11           3       124.20     23/07/2021                372.6
32  ALZR11          28       114.60     19/08/2021               3208.8
48  ALZR11          10       115.85     16/09/2021               1158.5

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
7   RECR11           3       105.12     23/07/2021               315.36
23  RECR11          32       102.68     19/08/2021              3285.76
39  RECR11          11       104.80     16/09/2021              1152.80

    Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
3  SANB11         100        29.13     19/08/2020               2913.0

   Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
0  ITSA4         300        13.06     12/07/2019               3918.0

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
16  VILG11           3       117.72     23/07/2021               353.16
35  VILG11          30       107.89     19/08/2021              3236.70
50  VILG11          11       108.18     16/09/2021              1189.98

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
18  VISC11           3       111.71     23/07/2021               335.13
36  VISC11          32       102.20     19/08/2021              3270.40
37  VISC11          32       102.24     19/08/2021              3271.68
51  VISC11          11       102.12     16/09/2021              1123.32

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
8   MCCI11           3       103.26     23/07/2021               309.78
24  MCCI11          32       101.40     19/08/2021              3244.80
40  MCCI11          11       100.94     16/09/2021              1110.34

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
13  MALL11           3        99.60     23/07/2021               298.80
30  MALL11          36        91.69     19/08/2021              3300.84
46  MALL11          12        95.95     16/09/2021              1151.40

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
20  VRTA11           3       112.25     23/07/2021               336.75
33  VRTA11          30       107.50     19/08/2021              3225.00
49  VRTA11          11       108.31     16/09/2021              1191.41

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
21  IRDM11           3       117.69     23/07/2021               353.07
34  IRDM11          29       111.40     19/08/2021              3230.60
53  IRDM11          10       114.52     16/09/2021              1145.20

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
15  VGIP11           3       102.19     23/07/2021               306.57
31  VGIP11          33        99.78     19/08/2021              3292.74
47  VGIP11          11       100.20     16/09/2021              1102.20

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
9   PVBI11           3        96.54     23/07/2021               289.62
27  PVBI11          35        93.15     19/08/2021              3260.25
41  PVBI11          13        89.22     16/09/2021              1159.86

   Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
4  WEGE3         180       33.715     12/08/2020               6068.7
5  WEGE3          20       35.930     08/03/2021                718.6

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
10  RBRP11           3        82.92     23/07/2021               248.76
26  RBRP11          44        74.78     19/08/2021              3290.32
42  RBRP11          16        73.73     16/09/2021              1179.68

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
12  XPLG11           3       112.13     23/07/2021               336.39
25  XPLG11          32       101.75     19/08/2021              3256.00
44  XPLG11          12        98.40     16/09/2021              1180.80

     Ativo  Quantidade  Compra (R$) Data da Compra  Soma Ponderada (R$)
11  HGRU11           3       120.78     23/07/2021               362.34
28  HGRU11          28       115.40     19/08/2021              3231.20
43  HGRU11          10       115.60     16/09/2021              1156.00

Calculando o preço médio em cada sub DataFrame

In [44]:
from pandas import DataFrame

ListaAtivos = []
ListaPrecoMedio = []

for nome in conjunto:

    ListaAtivos.append(nome)
    
    df2 = df.loc[ df['Ativo'] == nome ]
    
    SomaPesos = df2['Quantidade'].sum()

    SomaTotal = df2['Soma Ponderada (R$)'].sum()

    media = SomaTotal/SomaPesos
    
    ListaPrecoMedio.append(media)

dicionario = {'Ativo': ListaAtivos, 'Preço Médio de compra (R$)': ListaPrecoMedio}

df3 = DataFrame(dicionario)

df3

     Ativo  Preço Médio de compra (R$)
0    ITUB4                   36.102143
1   XPML11                  102.025714
2   HGLG11                  164.053000
3   BTLG11                  108.212045
4   ALZR11                  115.607317
5   RECR11                  103.346087
6   SANB11                   29.130000
7    ITSA4                   13.060000
8   VILG11                  108.632727
9   VISC11                  102.570897
10  MCCI11                  101.411304
11  MALL11                   93.157647
12  VRTA11                  108.026364
13  IRDM11                  112.592143
14  VGIP11                  100.032128
15  PVBI11                   92.347647
16   WEGE3                   33.936500
17  RBRP11                   74.900952
18  XPLG11                  101.557234
19  HGRU11                  115.842439

In [45]:
df3.to_csv('PrecosMedios.csv', index = False)